In [3]:
import numpy as np

In [4]:
zolo_people = ('Midhun','Devan','Vignesh')
a = np.array(zolo_people)
print(f"type of zolo_people : {type(zolo_people)},\ntype of a: {type(a)}")

type of zolo_people : <class 'tuple'>,
type of a: <class 'numpy.ndarray'>


In [5]:
twod_arr = [[1,2,4],[2,3,4],[5,6,7]]
b = np.array(twod_arr)
print(b)
type(b)

[[1 2 4]
 [2 3 4]
 [5 6 7]]


numpy.ndarray

In [6]:
2**8


256

In [7]:
c = np.random.randint(3,10,(3,3))
c

array([[3, 8, 6],
       [3, 6, 7],
       [7, 3, 9]])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
print(c,"\n\n",b)

[[3 8 6]
 [3 6 7]
 [7 3 9]] 

 [[1 2 4]
 [2 3 4]
 [5 6 7]]


In [10]:
b = c

In [11]:
b == c

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
type(4+3j)

complex

In [13]:
type(True)

bool

In [14]:
print(b,'\n\n',c)

[[3 8 6]
 [3 6 7]
 [7 3 9]] 

 [[3 8 6]
 [3 6 7]
 [7 3 9]]


In [15]:
np.dot(b,c)

array([[ 75,  90, 128],
       [ 76,  81, 123],
       [ 93, 101, 144]])

In [18]:
a = [4,'game',4+5j,4.3]
b = np.array(a)
b.dtype.name

'str2048'

In [22]:
c

array([[3, 8, 6],
       [3, 6, 7],
       [7, 3, 9]])

In [26]:
c.transpose()

array([[3, 3, 7],
       [8, 6, 3],
       [6, 7, 9]])

In [24]:
np.apply_along_axis(arr=c,axis=0,func1d=np.sum)

array([13, 17, 22])

### Playing with shapes of an array


In [27]:
a = np.random.random((3,4))
a.shape

(3, 4)

In [28]:
a

array([[0.11728408, 0.38199446, 0.93238183, 0.14945781],
       [0.10812672, 0.79361572, 0.13177134, 0.86185322],
       [0.67184884, 0.97715457, 0.9870648 , 0.79723184]])

In [29]:
b = a.reshape((4,3))
b

array([[0.11728408, 0.38199446, 0.93238183],
       [0.14945781, 0.10812672, 0.79361572],
       [0.13177134, 0.86185322, 0.67184884],
       [0.97715457, 0.9870648 , 0.79723184]])

In [30]:
b.shape = (12)
b

array([0.11728408, 0.38199446, 0.93238183, 0.14945781, 0.10812672,
       0.79361572, 0.13177134, 0.86185322, 0.67184884, 0.97715457,
       0.9870648 , 0.79723184])

In [35]:
a.shape = (2,2,3)
a

array([[[0.11728408, 0.38199446, 0.93238183],
        [0.14945781, 0.10812672, 0.79361572]],

       [[0.13177134, 0.86185322, 0.67184884],
        [0.97715457, 0.9870648 , 0.79723184]]])

In [32]:
b.ravel()

array([0.11728408, 0.38199446, 0.93238183, 0.14945781, 0.10812672,
       0.79361572, 0.13177134, 0.86185322, 0.67184884, 0.97715457,
       0.9870648 , 0.79723184])

In [36]:
a.ravel()

array([0.11728408, 0.38199446, 0.93238183, 0.14945781, 0.10812672,
       0.79361572, 0.13177134, 0.86185322, 0.67184884, 0.97715457,
       0.9870648 , 0.79723184])

### Vectorization and Broadcasting 

In [38]:
A = np.arange(0,16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
b = np.arange(0,4)
b

array([0, 1, 2, 3])

In [41]:
A+b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [42]:
structured = np.array([
                        (1, 'First', 0.5, 1+2j),
                        (2, 'Second', 1.3, 2-2j),
                        (3, 'Third', 0.8, 1+3j)
                    ]
                        ,dtype=('i2, a6, f4, c8'))
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [46]:
structured.dtype

dtype([('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])