# Numpy 

In [2]:
import numpy as np

## Creating Numpy Arrays

In [3]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [4]:
y = np.array(([5,4,3],(4,2,1),[3,2,1]))
y

array([[5, 4, 3],
       [4, 2, 1],
       [3, 2, 1]])

In [5]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.random.random((3,3))

array([[0.52260062, 0.14172337, 0.33676108],
       [0.51662206, 0.25053046, 0.03769225],
       [0.08389126, 0.15923253, 0.32039351]])

In [10]:
np.random.randint(5,10,(3,3))

array([[5, 8, 7],
       [6, 6, 5],
       [8, 9, 5]])

In [11]:
a = np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Matrix Product

In [12]:
a = np.random.randint(5,10,(3,3))
b =  np.random.randint(5,10,(3,3))
print(a,b,np.dot(a,b))

[[6 6 9]
 [8 8 6]
 [7 6 5]] [[8 9 7]
 [5 5 6]
 [8 7 5]] [[150 147 123]
 [152 154 134]
 [126 128 110]]


In [13]:
A = np.dot(a,b)
B = np.dot(b,a)
(A==B).all()

False

### Universal Function (Ufunc)

In [14]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.log(a)

C:\Users\HRITHI~1\AppData\Local\Temp/ipykernel_12132/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [16]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [17]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

### Aggregate Function

In [18]:
min(a)

0

In [20]:
max(a)

9

In [21]:
np.max(a)

9

In [22]:
a.sum()

45

In [23]:
a.mean()

4.5

In [24]:
a.std()

2.8722813232690143

## Indexing, Slicing and Iterating 

In [25]:
A

array([[150, 147, 123],
       [152, 154, 134],
       [126, 128, 110]])

In [34]:
A[:-1]

array([[150, 147, 123],
       [152, 154, 134]])

#### Aplly along the axis 

In [40]:
np.apply_along_axis(lambda x:x**0.5,axis=0,arr=A[:2,1:])

array([[12.12435565, 11.09053651],
       [12.40967365, 11.5758369 ]])

In [42]:
A

array([[150, 147, 123],
       [152, 154, 134],
       [126, 128, 110]])

## Shape Manipulation 

In [44]:
A.reshape(-1,1)

array([[150],
       [147],
       [123],
       [152],
       [154],
       [134],
       [126],
       [128],
       [110]])

In [45]:
A.reshape(1,-1)

array([[150, 147, 123, 152, 154, 134, 126, 128, 110]])

In [43]:
A.ravel()

array([150, 147, 123, 152, 154, 134, 126, 128, 110])

In [50]:
A.T

array([[150, 152, 126],
       [147, 154, 128],
       [123, 134, 110]])

In [51]:
A.transpose()

array([[150, 152, 126],
       [147, 154, 128],
       [123, 134, 110]])

## Joining Arrrays 

In [53]:
A = np.ones((3, 3))
B = np.zeros((3, 3))
np.hstack([A,B])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [54]:
np.vstack([A,B])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
C = np.random.random((3,3))
C

array([[0.98668228, 0.33651635, 0.53573907],
       [0.57434682, 0.85900297, 0.41415632],
       [0.69075737, 0.51550579, 0.07163049]])

In [56]:
np.column_stack([A,B,C])

array([[1.        , 1.        , 1.        , 0.        , 0.        ,
        0.        , 0.98668228, 0.33651635, 0.53573907],
       [1.        , 1.        , 1.        , 0.        , 0.        ,
        0.        , 0.57434682, 0.85900297, 0.41415632],
       [1.        , 1.        , 1.        , 0.        , 0.        ,
        0.        , 0.69075737, 0.51550579, 0.07163049]])

In [57]:
np.row_stack([A,B,C])

array([[1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.98668228, 0.33651635, 0.53573907],
       [0.57434682, 0.85900297, 0.41415632],
       [0.69075737, 0.51550579, 0.07163049]])

In [58]:
np.hstack([A,B,C])

array([[1.        , 1.        , 1.        , 0.        , 0.        ,
        0.        , 0.98668228, 0.33651635, 0.53573907],
       [1.        , 1.        , 1.        , 0.        , 0.        ,
        0.        , 0.57434682, 0.85900297, 0.41415632],
       [1.        , 1.        , 1.        , 0.        , 0.        ,
        0.        , 0.69075737, 0.51550579, 0.07163049]])

## Splitting Arrays 

In [61]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
np.hsplit(A,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [63]:
np.vsplit(A,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

### Copy of an Object 

In [64]:
a = np.random.randint(1,10,(3,3))
a

array([[2, 9, 2],
       [5, 5, 7],
       [7, 8, 7]])

In [66]:
b = a.copy()
c = a
print(id(a),id(c),id(b))

2181836430096 2181836430096 2181836540976


### Structured Array 

In [68]:
structured = np.array([(1,'First',0.5,1+2j),
                        (2,'Second',1.3,2-2j), 
                        (3,'Third',0.8,1+3j)],
                        dtype=[('id','i2'),('position','a6'),('value','f4'),('complex','c8')])

In [70]:
structured.dtype

dtype([('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

## Reading CSV

In [ ]:
data = np.genfromtxt('data.csv',delimiter=',',names=True)