## DA LAB 2


### *1.* Create 2D numpy array using arange() function.

In [2]:
import numpy as np 
a = np.arange(start=1, stop=10, step=2)
a

array([1, 3, 5, 7, 9])

### *2.* Create 3D array from 1D numpy array.

In [5]:
a = np.array(range(0,9))
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 3. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [6]:
x =  np.arange(2, 11).reshape(3,3)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 4. Write a NumPy program to reverse an array (first element becomes last).

In [8]:
a = np.array(range(0,10))
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 5. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [9]:
m = np.array([[1,1,1],[1,0,1],[1,1,1]])
m

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

### 6. Create a 2D array A with 4x4 size then split it into 3 different arrays B(1x4),C(2x4) and D(2x4).

In [12]:
a = np.random.randint(7,size=(4,4))
a

array([[4, 2, 1, 5],
       [2, 2, 0, 2],
       [2, 5, 5, 4],
       [6, 3, 6, 0]])

In [15]:
a[0:1]

array([[4, 2, 1, 5]])

In [16]:
a[0:2]

array([[4, 2, 1, 5],
       [2, 2, 0, 2]])

In [18]:
a[2:]

array([[2, 5, 5, 4],
       [6, 3, 6, 0]])

### 7. Perform element wise multiplication of arrays C and D in question 6.

In [19]:
a[0:2]*a[2:]

array([[ 8, 10,  5, 20],
       [12,  6,  0,  0]])

### 8. Create a numpy array matrix of size 3x4. Find column which has highest sum and display.

In [35]:
a = np.random.randint(7,size=(3,4))
b =list(a.sum(axis=1))
print(a)
print("The highest sum column is {}".format(b.index(max(b))))



[[0 3 5 0]
 [6 3 1 2]
 [1 4 5 2]]
The highest sum column is 1


---
## By Hrithik 